# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Environment
version:      0.02
version_from: lib/Test/Environment.pm
installdirs:  site
requires:
    Carp::Clan:                    0
    File::Basename:                0
    File::Slurp:                   0
    String::ShellQuote:            0
    Test::Differences:             0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
